version: 2

terraform: &terraform
  docker:
    - image: hashicorp/terraform:light
  working_directory: /tmp/workspace/terraform

jobs:
  build:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init -input=false
      - run:
          name: terraform validate
          command: terraform validate
      - run:
          name: Install tflint
          command: curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip && rm tflint.zip
      - run:
          name: Check Terraform configurations with tflint
          command: tflint
      - run:
          name: terraform plan
          command: terraform plan -input=false

workflows:
  version: 2
  build:
    jobs:
      - build
